### ISSUE TITLE
Suggestion regarding installation Method 1 (without Elasticsearch)

### ISSUE THREAD

**Issue by ak77-prime** [AdobeDocs/commerce-merchant-services.en#14]
Issue in ./help/live-search/install.md

I suggest adding a side note indicating how to verify whether LiveSearch is used as the search engine.

Currently, the command to determine the Search Engine configuration ``bin/magento config:show catalog/search/engine``

However, it seems that even if you have enabled Live Search, the command would always indicate Elasticsearch - and I believe if LiveSearch fails then it would fall back to Elasticsearch

**Comment by erikmarr** [comment]
Hi @dobooth, would you mind taking a look?

**Comment by meker12** [comment]
Issue ported to Adobe corporate repo.
