### ISSUE TITLE
Module magento/module-live-search-metrics not found when install magento/live-search ^2.0

### ISSUE THREAD

**Issue by chinhnm** [AdobeDocs/commerce-merchant-services.en#16]
Hi Magento team, when I install live search 2.0, I got this error magento/module-live-search-metrics not found when run **composer require magento/live-search**
![image](https://user-images.githubusercontent.com/14218275/208067008-ca19f3f5-2914-445c-bd54-ca00561c4e0f.png)

My magento version is 2.4.3-p1, I see in the document said: "It support for magento 2.4.x". Can you please help me on this bug?
Thanks

More information: 
I have to run require:'*' & install magento/live-search 1.2.0 in my project and it got error **Unable to retrieve category breadcrumbs data** when re-index Category Feed. So I think better I will use the newest version.

**Comment by dobooth** [comment]
Thanks for the issue. Since you wrote this, the requirements for Live Search are now Commerce 2.4.4 and higher. Hopefully you can upgrade.
