### ISSUE TITLE
Events Field Description

### ISSUE THREAD

**Issue by jan-kaminsky** [AdobeDocs/commerce-merchant-services.en#19]
Issue in ./help/live-search/rules-add.md

I believe that in order to "Pin" a product in live search, the product must be in the results set. It cannot be any specific product in the catalog. 

In this case, the description of the "Pin a Product" event should state that only products returned in the result set can be pinned which would take out any ambiguity. A Client had misinterpreted and was attempting to add a product that wasn't returned in the result set to no avail.

Thank you!

**Comment by dobooth** [comment]
Fix will be merged shortly. Thanks for this!
