### ISSUE TITLE
remove 'and Visible In Advanced Search'

### ISSUE THREAD

**Issue by cscrewvala** [AdobeDocs/commerce-merchant-services.en#43]
Issue in ./help/live-search/indexing.md

"When enabled, Search Weight and Visible in Advanced Search can be set for the attribute."

This may be misleading, as my understanding is that Advanced Search is not applicable or usable on the storefront when Live Search is used rather than Open Search, as it is a older feature (just a storefront UI feature really), linked only to Open Search, and not available to use with Live Search. That is my understanding (worth confirming) e.g. on the Live Search demo environment, the advanced search page is technically available in the Luma theme, but the search does not work, as it would need the Open Search index: 
No results when advanced searching for tank - https://saas.adobedemo.com/catalogsearch/advanced/result/?name=tank&sku=&description=&short_description=&price%5Bfrom%5D=&price%5Bto%5D=

Results when Live searching for tank - https://saas.adobedemo.com/catalogsearch/result/?q=tank

---
So the edit should be to remove 'and Visible In Advanced Search', to avoid confusing merchants.

**Comment by erikmarr** [comment]
Thanks for the feedback @cscrewvala. You are correct this is misleading. Here's a PR with the fix: https://git.corp.adobe.com/AdobeDocs/commerce-merchant-services.en/pull/603
